import abc
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional

class ProblemReport:
    """
    Represents a report generated by a detector when a problematic agent behavior is identified.
    """
    def __init__(self,
                 detector_id: str,
                 type: str,
                 description: str,
                 severity: str = "medium",
                 details: Optional[Dict[str, Any]] = None):
        """
        Initializes a ProblemReport.

        Args:
            detector_id (str): A unique identifier for the detector that generated this report.
            type (str): The type of problem detected (e.g., "loop", "stall", "repetition").
            description (str): A human-readable description of the detected problem.
            severity (str): The severity level of the problem (e.g., "low", "medium", "high").
            details (Optional[Dict[str, Any]]): Additional structured details about the problem,
                                                 such as specific states, timestamps, or trace segments.
        """
        if not detector_id:
            raise ValueError("detector_id cannot be empty.")
        if not type:
            raise ValueError("type cannot be empty.")
        if not description:
            raise ValueError("description cannot be empty.")

        self.detector_id = detector_id
        self.type = type
        self.description = description
        self.severity = severity
        self.details = details if details is not None else {}

    def __repr__(self) -> str:
        return (f"ProblemReport(detector_id='{self.detector_id}', type='{self.type}', "
                f"description='{self.description}', severity='{self.severity}', details={self.details})")

    def to_dict(self) -> Dict[str, Any]:
        """Converts the ProblemReport to a dictionary."""
        return {
            "detector_id": self.detector_id,
            "type": self.type,
            "description": self.description,
            "severity": self.severity,
            "details": self.details
        }


class BaseDetector(ABC):
    """
    Abstract base class for all detectors in the meta-monitoring framework.

    Detectors are responsible for identifying problematic agent behaviors
    based on the historical state provided by the StateManager.
    """

    def __init__(self, detector_id: str):
        """
        Initializes the BaseDetector.

        Args:
            detector_id (str): A unique identifier for this detector instance.
        """
        if not detector_id:
            raise ValueError("detector_id cannot be empty.")
        self.detector_id = detector_id

    @abstractmethod
    def detect(self, state_history: Any) -> Optional[ProblemReport]:
        """
        Analyzes the agent's historical state to detect problematic patterns or behaviors.

        This method should be implemented by concrete detector classes.

        Args:
            state_history (Any): A representation of the agent's historical state,
                                 typically provided by the StateManager. This could be
                                 a list of states, a specific window of states, or
                                 a more complex data structure.

        Returns:
            Optional[ProblemReport]: A ProblemReport if an issue is detected,
                                     otherwise None.
        """
        pass

    def get_id(self) -> str:
        """
        Returns the unique identifier of this detector.
        """
        return self.detector_id