```python
import os
import logging
import uuid
from typing import List, Dict, Any

import chromadb
from chromadb.api.models.Collection import Collection
from chromadb.utils.embedding_functions import EmbeddingFunction, Documents, Embeddings

# Assuming these modules exist as per project structure
from config import VECTOR_STORE_PATH
from llm_client import LLMClient # Import needed for type hinting and to use its get_embedding method

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# --- Custom Chroma Embedding Function Wrapper ---
class ChromaLLMEmbeddingFunction(EmbeddingFunction):
    """
    A wrapper class to make LLMClient's get_embedding method compatible with ChromaDB.
    This allows ChromaDB to use the centralized LLMClient for embedding generation.
    """
    def __init__(self, llm_client: LLMClient):
        self.llm_client = llm_client
        if not hasattr(self.llm_client, 'get_embedding') or not callable(self.llm_client.get_embedding):
            raise AttributeError(
                "LLMClient instance passed to VectorStoreManager must have a 'get_embedding' method."
            )

    def __call__(self, input: Documents) -> Embeddings:
        """
        Embeds a list of documents using the LLMClient's get_embedding method.
        It is assumed that LLMClient.get_embedding can handle a list of texts
        or is called for each text individually.
        """
        try:
            # Call get_embedding for each document. LLMClient should ideally handle batching
            # for efficiency if it's an API call.
            return [self.llm_client.get_embedding(text) for text in input]
        except Exception as e:
            logger.error(f"Error generating embeddings with LLMClient: {e}")
            raise

# --- VectorStoreManager Class ---
class VectorStoreManager:
    """
    Manages the creation, updating, and querying of the vector database.
    It uses ChromaDB as the underlying vector store and integrates with the
    LLMClient for generating embeddings for both documents and queries.
    Stores embeddings of processed chunks in data/vector_store/.
    """

    COLLECTION_NAME = "rag_context_collection" # A default name for the ChromaDB collection

    def __init__(self, llm_client: LLMClient):
        """
        Initializes the VectorStoreManager.

        Args:
            llm_client: An instance of LLMClient providing embedding capabilities.
                        Assumes llm_client has a `get_embedding(text: str) -> List[float]` method.
        """
        self.vector_store_path = VECTOR_STORE_PATH
        self.llm_client = llm_client

        # Ensure the vector store directory exists
        try:
            os.makedirs(self.vector_store_path, exist_ok=True)
            logger.info(f"Initialized VectorStoreManager with path: {self.vector_store_path}")
        except OSError as e:
            logger.error(f"Failed to create vector store directory at {self.vector_store_path}: {e}")
            raise

        # Initialize ChromaDB persistent client
        try:
            self.client = chromadb.PersistentClient(path=self.vector_store_path)
            logger.info("ChromaDB persistent client initialized.")
        except Exception as e:
            logger.error(f"Failed to initialize ChromaDB client with path {self.vector_store_path}: {e}")
            raise

        # Initialize the custom embedding function wrapper
        self.embedding_function = ChromaLLMEmbeddingFunction(self.llm_client)
        # Get or create the ChromaDB collection using the custom embedding function
        self.collection = self._get_or_create_collection()

    def _get_or_create_collection(self) -> Collection:
        """
        Gets an existing ChromaDB collection or creates a new one if it doesn't exist,
        using the custom embedding function for all operations.
        """
        try:
            collection = self.client.get_or_create_collection(
                name=self.COLLECTION_NAME,
                embedding_function=self.embedding_function # Pass the custom embedding function here
            )
            logger.info(f"ChromaDB collection '{self.COLLECTION_NAME}' loaded or created.")
            return collection
        except Exception as e:
            logger.error(f"Failed to get or create ChromaDB collection '{self.COLLECTION_NAME}': {e}")
            raise

    def add_documents(self, chunks: List[Dict[str, Any]]) -> List[str]:
        """
        Adds a list of document chunks to the vector store.
        Each chunk dict should contain 'text' and optionally 'metadata'.
        Embeddings for these chunks will be generated by the configured LLMClient
        via the custom ChromaLLMEmbeddingFunction.

        Args:
            chunks: A list of dictionaries, where each dict has at least a 'text' key
                    (str) and can optionally have a 'metadata' key (dict).
                    Example: [{'text': '...', 'metadata': {'source': 'doc1'}}]

        Returns:
            A list of unique IDs for the added documents. Returns an empty list
            if no chunks are added or an error occurs.
        """
        if not chunks:
            logger.warning("No chunks provided to add_documents.")
            return []

        documents_to_add = [chunk['text'] for chunk in chunks]
        metadatas_to_add = [chunk.get('metadata', {}) for chunk in chunks]
        # Generate unique IDs for each chunk to be added
        ids_to_add = [str(uuid.uuid4()) for _ in chunks]

        try:
            # ChromaDB's add method will automatically use the collection's embedding_function
            # to embed the raw documents before storing them.
            self.collection.add(
                documents=documents_to_add,
                metadatas=metadatas_to_add,
                ids=ids_to_add
            )
            logger.info(f"Successfully added {len(documents_to_add)} documents to the vector store.")
            return ids_to_add
        except Exception as e:
            logger.error(f"Failed to add documents to vector store: {e}")
            return []

    def query_vector_store(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
        """
        Queries the vector store for the most similar documents to the given query.
        The query string will be embedded by the configured LLMClient
        via the custom ChromaLLMEmbeddingFunction.

        Args:
            query: The natural language query string.
            k: The number of top similar documents to retrieve. Defaults to 5.

        Returns:
            A list of dictionaries, where each dict contains 'text', 'metadata', and 'distance'
            for the retrieved documents. Returns an empty list if no results are found or an
            error occurs.
        """
        if not query:
            logger.warning("Query string is empty for query_vector_store.")
            return []

        try:
            # ChromaDB's query method automatically uses the collection's embedding_function
            # to embed the query_texts before performing the similarity search.
            results = self.collection.query(
                query_texts=[query],
                n_results=k,
                include=['documents', 'metadatas', 'distances'] # Request full document content, metadata, and distance
            )

            retrieved_docs = []
            if results and results['documents'] and results['documents'][0]:
                # The results are typically nested lists (one sublist per query in query_texts)
                for i in range(len(results['documents'][0])):
                    doc = {
                        'text': results['documents'][0][i],
                        'metadata': results['metadatas'][0][i] if results['metadatas'] and results['metadatas'][0] else {},
                        'distance': results['distances'][0][i] if results['distances'] and results['distances'][0] else None
                    }
                    retrieved_docs.append(doc)
            logger.info(f"Retrieved {len(retrieved_docs)} documents for query: '{query[:50]}...'")
            return retrieved_docs
        except Exception as e:
            logger.error(f"Failed to query vector store: {e}")
            return []

    def clear_vector_store(self) -> None:
        """
        Clears all documents from the vector store collection.
        This operation effectively deletes the existing collection and
        recreates an empty one, resetting the vector store.
        """
        try:
            self.client.delete_collection(name=self.COLLECTION_NAME)
            # Recreate an empty collection after deletion
            self.collection = self._get_or_create_collection()
            logger.info(f"Vector store collection '{self.COLLECTION_NAME}' cleared.")
        except Exception as e:
            logger.error(f"Failed to clear vector store collection '{self.COLLECTION_NAME}': {e}")
            raise

    def count_documents(self) -> int:
        """
        Returns the number of documents currently stored in the vector store collection.
        """
        try:
            return self.collection.count()
        except Exception as e:
            logger.error(f"Failed to count documents in vector store: {e}")
            return 0
```