```python
import json
from typing import Dict, Any, Optional, List

# Assuming these imports exist in the project structure
from src.utils.llm_interface import LLMInterface
from src.utils.schemas import ToolCall, ToolSchema # Pydantic models for tool calls and schemas


class ValidationAgent:
    def __init__(self, llm_interface: LLMInterface, model_name: str = "gpt-4-turbo"):
        """
        Initializes the ValidationAgent, a meta-agent responsible for reviewing
        and correcting proposed tool calls.

        Args:
            llm_interface (LLMInterface): An instance of an LLM client,
                                          e.g., from src.utils.llm_interface.
            model_name (str): The name of the LLM model to use for validation.
                              (e.g., "gpt-4-turbo", "claude-3-opus-20240229").
        """
        self.llm = llm_interface
        self.model_name = model_name

    def _format_tool_schemas(self, tool_schemas: List[ToolSchema]) -> str:
        """
        Formats a list of Pydantic ToolSchema objects into a readable JSON string
        for inclusion in the LLM prompt. Each schema is individually dumped to JSON.

        Args:
            tool_schemas (List[ToolSchema]): A list of Pydantic ToolSchema objects.

        Returns:
            str: A multi-line string with JSON representations of each tool schema.
        """
        formatted_schemas = []
        for schema in tool_schemas:
            # Pydantic v2 .model_dump() returns a dict, which is then json.dumps'd.
            # Using indent for readability in the prompt.
            formatted_schemas.append(json.dumps(schema.model_dump(), indent=2))
        return "\n---\n".join(formatted_schemas)

    def validate_and_correct(
        self,
        user_query: str,
        primary_agent_proposed_tool_call: ToolCall,
        available_tool_schemas: List[ToolSchema],
    ) -> Dict[str, Any]:
        """
        Reviews a primary agent's proposed tool call for logical and contextual correctness
        using an LLM meta-agent. If errors are found, it proposes corrections.

        Args:
            user_query (str): The original user request.
            primary_agent_proposed_tool_call (ToolCall): The tool call proposed by the primary agent.
                                                          Expected to be a Pydantic ToolCall object.
            available_tool_schemas (List[ToolSchema]): A list of available tool schemas
                                                       (Pydantic ToolSchema objects).

        Returns:
            Dict[str, Any]: A dictionary containing validation status, reasoning, and potentially a
                            corrected tool call (as a Pydantic ToolCall object).
                            Possible 'status' values: "valid", "invalid", "no_tool", "error".

                            Example for "valid":
                            {
                                "status": "valid",
                                "reasoning": "Tool call is perfectly aligned with user intent and schema.",
                                "corrected_tool_call": ToolCall(tool_name="get_weather", arguments={"location": "London"})
                            }
                            Example for "invalid":
                            {
                                "status": "invalid",
                                "reasoning": "Incorrect argument value for 'location', should be 'London'.",
                                "corrected_tool_call": ToolCall(tool_name="get_weather", arguments={"location": "London"})
                            }
                            Example for "no_tool":
                            {
                                "status": "no_tool",
                                "reasoning": "User query cannot be fulfilled by any available tool.",
                                "corrected_tool_call": None
                            }
                            Example for "error":
                            {
                                "status": "error",
                                "reasoning": "Failed to parse LLM response or unexpected format.",
                                "corrected_tool_call": None
                            }
        """
        system_prompt = (
            "You are a highly analytical and critical validation agent for an AI system. "
            "Your task is to meticulously review a proposed tool call generated by a primary AI agent "
            "against the original user query and available tool schemas. "
            "Your goal is to ensure 100% accuracy in tool selection, argument extraction, and logical consistency. "
            "Carefully check for:\n"
            "1.  **Correct Tool Selection**: Is the chosen tool the most appropriate for the user's request?\n"
            "2.  **Argument Completeness**: Are all required arguments for the chosen tool present according to its schema?\n"
            "3.  **Argument Correctness**: Are the argument values accurately extracted from the user query "
            "    and do they conform to the tool's schema (e.g., data types, constraints, logical sense)?\n"
            "4.  **Logical Consistency**: Is the entire tool call logically sound in the context of the user's intent?\n"
            "5.  **Ambiguity/Missing Information**: If the user query is ambiguous or lacks crucial information, "
            "    consider if the tool call is still the best approach or if a 'no_tool' action with a "
            "    request for clarification would be better.\n\n"
            "If the proposed tool call is perfect and requires no changes, respond with `\"status\": \"valid\"`. "
            "If there are *any* errors, logical inconsistencies, or opportunities for improvement, "
            "respond with `\"status\": \"invalid\"` and provide a `\"corrected_tool_call\"` object. "
            "If the user's intent cannot be fulfilled by any available tool, or if the request is too ambiguous "
            "to proceed with a tool call, respond with `\"status\": \"no_tool\"` and explain why. "
            "When providing a `corrected_tool_call`, ensure it strictly adheres to one of the provided tool schemas "
            "and represents the best possible interpretation of the user's request.\n\n"
            "Respond ONLY with a JSON object. The JSON should strictly adhere to the following structure:\n"
            "{\n"
            "  \"status\": \"valid\" | \"invalid\" | \"no_tool\",\n"
            "  \"reasoning\": \"A detailed explanation of your validation findings or proposed correction.\",\n"
            "  \"corrected_tool_call\": { // Optional. Required if status is 'invalid'. If 'valid', should be the same as primary agent's call. If 'no_tool', it should be null.\n"
            "    \"tool_name\": \"<tool_name_string>\",\n"
            "    \"arguments\": { \"<arg_name>\": \"<arg_value>\", ... }\n"
            "  } | null\n"
            "}"
        )

        # Convert the Pydantic ToolCall object to a dictionary for LLM consumption
        proposed_call_dict = primary_agent_proposed_tool_call.model_dump()

        user_message_content = (
            f"Original User Query: {user_query}\n\n"
            f"Primary Agent's Proposed Tool Call:\n```json\n{json.dumps(proposed_call_dict, indent=2)}\n```\n\n"
            f"Available Tool Schemas:\n```json\n{self._format_tool_schemas(available_tool_schemas)}\n```\n\n"
            f"Please provide your validation and potential correction in the specified JSON format."
        )

        response_text: str = "" # Initialize to ensure it's always defined for error messages

        try:
            response_text = self.llm.get_completion(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message_content}
                ],
                # Request JSON object response if the LLM provider supports it
                response_format={"type": "json_object"} if self.llm.supports_json_mode(self.model_name) else None
            )

            validation_result = json.loads(response_text)

            # --- Basic validation of the LLM's response structure ---
            if not isinstance(validation_result, dict) or "status" not in validation_result or "reasoning" not in validation_result:
                raise ValueError("LLM response is not in the expected JSON format or missing required keys (status, reasoning).")

            status = validation_result["status"]
            reasoning = validation_result["reasoning"]
            corrected_tool_call_dict = validation_result.get("corrected_tool_call")

            final_corrected_tool_call: Optional[ToolCall] = None

            if status == "valid":
                # If valid, the corrected call should either be the original one or what the LLM provided.
                if corrected_tool_call_dict:
                    try:
                        final_corrected_tool_call = ToolCall(**corrected_tool_call_dict)
                    except Exception as e:
                        return {
                            "status": "error",
                            "reasoning": (
                                f"Validation agent marked as 'valid' but provided a malformed 'corrected_tool_call'. "
                                f"Error: {e}. Original reasoning: {reasoning}"
                            ),
                            "corrected_tool_call": None
                        }
                else:
                    # If LLM says 'valid' but provides no corrected_tool_call, assume original is correct.
                    final_corrected_tool_call = primary_agent_proposed_tool_call
            elif status == "invalid":
                if not corrected_tool_call_dict:
                    # If invalid, a corrected_tool_call is mandatory
                    return {
                        "status": "error",
                        "reasoning": (
                            f"Validation agent marked as 'invalid' but did not provide 'corrected_tool_call'. "
                            f"Original reasoning: {reasoning}"
                        ),
                        "corrected_tool_call": None
                    }
                try:
                    final_corrected_tool_call = ToolCall(**corrected_tool_call_dict)
                except Exception as e:
                    return {
                        "status": "error",
                        "reasoning": (
                            f"Validation agent provided a malformed 'corrected_tool_call' for an 'invalid' status. "
                            f"Error: {e}. Original reasoning: {reasoning}"
                        ),
                        "corrected_tool_call": None
                    }
            elif status == "no_tool":
                # For 'no_tool', corrected_tool_call should be None or null
                final_corrected_tool_call = None
            else:
                # Catch any unexpected status values returned by the LLM
                return {
                    "status": "error",
                    "reasoning": f"Validation agent returned an unexpected status: '{status}'. Original reasoning: {reasoning}",
                    "corrected_tool_call": None
                }
            
            return {
                "status": status,
                "reasoning": reasoning,
                "corrected_tool_call": final_corrected_tool_call
            }

        except json.JSONDecodeError as e:
            return {
                "status": "error",
                "reasoning": (
                    f"Validation agent produced malformed JSON response. Error: {e}. "
                    f"Raw response (first 500 chars): {response_text[:500]}..." if response_text else "N/A"
                ),
                "corrected_tool_call": None
            }
        except ValueError as e:
            return {
                "status": "error",
                "reasoning": (
                    f"Validation agent response validation failed: {e}. "
                    f"Raw response (first 500 chars): {response_text[:500]}..." if response_text else "N/A"
                ),
                "corrected_tool_call": None
            }
        except Exception as e:
            # Catch any other unexpected errors during the process
            return {
                "status": "error",
                "reasoning": f"An unexpected error occurred during validation agent processing: {e}",
                "corrected_tool_call": None
            }

```