import os
from dotenv import load_dotenv

load_dotenv() # Load environment variables from .env file

class VectorDBConfig:
    """
    Configuration settings for the Vector Database.
    This class centralizes parameters for various vector database providers
    to ensure consistency and easy management across the system.
    """

    # --- General Vector DB Settings ---
    # The dimension of the embeddings generated by src/utils/embedding_model.py.
    # E.g., OpenAI text-embedding-ada-002 is 1536. Must match your chosen embedding model.
    EMBEDDING_DIMENSION: int = int(os.getenv("EMBEDDING_DIMENSION", "1536"))
    DEFAULT_TOP_K: int = int(os.getenv("VECTOR_DB_DEFAULT_TOP_K", "5")) # Default number of results to retrieve
    UPSERT_BATCH_SIZE: int = int(os.getenv("VECTOR_DB_UPSERT_BATCH_SIZE", "100")) # General batch size for upsert operations

    # --- Active Vector Database Provider Selection ---
    # Set this environment variable to 'PINECONE', 'CHROMADB', 'WEAVIATE', 'FAISS', etc.
    # to select the active vector database provider for the system.
    VECTOR_DB_PROVIDER: str = os.getenv("VECTOR_DB_PROVIDER", "CHROMADB").upper()

    # --- Pinecone Configuration ---
    PINECONE_API_KEY: str = os.getenv("PINECONE_API_KEY", "")
    PINECONE_ENVIRONMENT: str = os.getenv("PINECONE_ENVIRONMENT", "") # e.g., "us-east-1"
    PINECONE_INDEX_NAME: str = os.getenv("PINECONE_INDEX_NAME", "rag-intelligent-index")
    PINECONE_NAMESPACE: str = os.getenv("PINECONE_NAMESPACE", "default") # Optional: for multi-tenancy within an index

    # --- ChromaDB Configuration ---
    # For persistent local ChromaDB
    CHROMADB_PERSIST_DIRECTORY: str = os.getenv("CHROMADB_PERSIST_DIRECTORY", "./data/chroma_db")
    CHROMADB_COLLECTION_NAME: str = os.getenv("CHROMADB_COLLECTION_NAME", "intelligent_rag_collection")
    # For client/server ChromaDB
    CHROMADB_USE_HTTP: bool = os.getenv("CHROMADB_USE_HTTP", "False").lower() == "true"
    CHROMADB_HOST: str = os.getenv("CHROMADB_HOST", "localhost")
    CHROMADB_PORT: int = int(os.getenv("CHROMADB_PORT", "8000"))

    # --- Weaviate Configuration ---
    WEAVIATE_URL: str = os.getenv("WEAVIATE_URL", "http://localhost:8080")
    WEAVIATE_API_KEY: str = os.getenv("WEAVIATE_API_KEY", "") # For Weaviate Cloud (WCS) or authenticated instances
    WEAVIATE_GRPC_PORT: int = int(os.getenv("WEAVIATE_GRPC_PORT", "50051")) # For gRPC connections, if applicable
    WEAVIATE_CLASS_NAME: str = os.getenv("WEAVIATE_CLASS_NAME", "Document") # Default class name for documents

    # --- FAISS (Local) Configuration ---
    FAISS_INDEX_PATH: str = os.getenv("FAISS_INDEX_PATH", "./data/faiss_index.bin")
    FAISS_METADATA_PATH: str = os.getenv("FAISS_METADATA_PATH", "./data/faiss_metadata.json") # To store metadata alongside FAISS index

    @staticmethod
    def validate_config():
        """
        Validates the configuration for the selected vector database provider.
        Raises a ValueError if critical configuration parameters are missing or invalid
        for the chosen provider.
        """
        provider = VectorDBConfig.VECTOR_DB_PROVIDER

        if not VectorDBConfig.EMBEDDING_DIMENSION > 0:
            raise ValueError(f"EMBEDDING_DIMENSION must be a positive integer, got {VectorDBConfig.EMBEDDING_DIMENSION}")
        if not VectorDBConfig.DEFAULT_TOP_K > 0:
            raise ValueError(f"DEFAULT_TOP_K must be a positive integer, got {VectorDBConfig.DEFAULT_TOP_K}")
        if not VectorDBConfig.UPSERT_BATCH_SIZE > 0:
            raise ValueError(f"UPSERT_BATCH_SIZE must be a positive integer, got {VectorDBConfig.UPSERT_BATCH_SIZE}")

        if provider == "PINECONE":
            if not VectorDBConfig.PINECONE_API_KEY:
                raise ValueError("PINECONE_API_KEY must be set in environment variables for Pinecone.")
            if not VectorDBConfig.PINECONE_ENVIRONMENT:
                raise ValueError("PINECONE_ENVIRONMENT must be set in environment variables for Pinecone.")
        elif provider == "CHROMADB":
            if VectorDBConfig.CHROMADB_USE_HTTP:
                if not VectorDBConfig.CHROMADB_HOST:
                    raise ValueError("CHROMADB_HOST must be set for ChromaDB HTTP client mode.")
                if not VectorDBConfig.CHROMADB_PORT:
                    raise ValueError("CHROMADB_PORT must be set for ChromaDB HTTP client mode.")
            else:
                if not VectorDBConfig.CHROMADB_PERSIST_DIRECTORY:
                    # In-memory ChromaDB is an option, but usually for testing. Warn if not persistent.
                    print("Warning: CHROMADB_PERSIST_DIRECTORY not set. ChromaDB will use an in-memory ephemeral database.")
        elif provider == "WEAVIATE":
            if not VectorDBConfig.WEAVIATE_URL:
                raise ValueError("WEAVIATE_URL must be set in environment variables for Weaviate.")
            # WEAVIATE_API_KEY is optional depending on Weaviate instance setup (local vs. cloud, auth)
        elif provider == "FAISS":
            # FAISS is local, its paths are important but don't require external validation like API keys.
            if not VectorDBConfig.FAISS_INDEX_PATH:
                print("Warning: FAISS_INDEX_PATH not set. Defaulting to './data/faiss_index.bin'.")
            if not VectorDBConfig.FAISS_METADATA_PATH:
                print("Warning: FAISS_METADATA_PATH not set. Defaulting to './data/faiss_metadata.json'.")
        else:
            raise ValueError(f"Unsupported VECTOR_DB_PROVIDER: '{provider}'. "
                             "Please set VECTOR_DB_PROVIDER to one of 'PINECONE', 'CHROMADB', 'WEAVIATE', 'FAISS'.")

# Optionally, run validation automatically when the config is loaded
try:
    VectorDBConfig.validate_config()
except ValueError as e:
    print(f"VectorDB Configuration Error: {e}")
    # Depending on the application's criticality, you might want to exit here.
    # For a prototype, a warning might suffice, but for production, this should halt startup.
    # import sys
    # sys.exit(1)