from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class Query(BaseModel):
    """
    Represents the user's input query.
    """
    text: str = Field(..., description="The original text of the user query.")
    query_id: Optional[str] = Field(None, description="An optional unique identifier for the query.")
    metadata: Dict[str, Any] = Field({}, description="Additional metadata related to the query, e.g., intent, user_id.")

class Document(BaseModel):
    """
    Represents a single document or a chunk of text retrieved from a knowledge source.
    """
    id: str = Field(..., description="A unique identifier for the document or chunk.")
    text: str = Field(..., description="The textual content of the document/chunk.")
    metadata: Dict[str, Any] = Field(
        {}, description="Additional metadata about the document, e.g., source, URL, title, page_number, chunk_index."
    )

class RetrievalResult(BaseModel):
    """
    Encapsulates a retrieved Document along with its relevance score and other retrieval-specific information.
    """
    document: Document = Field(..., description="The retrieved document object.")
    score: float = Field(..., description="The relevance score assigned to this document by the retriever/reranker.")
    retriever_name: Optional[str] = Field(
        None, description="The name of the retriever module that identified this document (e.g., 'vector', 'keyword')."
    )
    stage: Optional[str] = Field(
        None, description="The pipeline stage where this result was produced or last processed (e.g., 'initial_retrieval', 'reranking')."
    )
    metadata: Dict[str, Any] = Field({}, description="Additional retrieval-specific metadata, e.g., embedding_distance, search_query_used.")

class Context(BaseModel):
    """
    Represents the aggregated context provided to the LLM for generation, typically a list of retrieval results
    after re-ranking, filtering, and compression.
    """
    retrieval_results: List[RetrievalResult] = Field(
        [], description="A list of RetrievalResult objects forming the context."
    )
    summarized_text: Optional[str] = Field(
        None, description="An optional summarized version of the entire context, if compression was applied."
    )
    metadata: Dict[str, Any] = Field(
        {}, description="Additional context-specific metadata, e.g., compression_strategy, token_count."
    )

class PipelineResult(BaseModel):
    """
    Represents the final output of the entire RAG pipeline.
    """
    query: Query = Field(..., description="The original query that initiated the pipeline.")
    generated_response: str = Field(..., description="The final text generated by the LLM based on the query and context.")
    retrieved_context: Context = Field(..., description="The Context object used to generate the response.")
    pipeline_trace: Optional[Dict[str, Any]] = Field(
        None, description="A dictionary to trace the execution path and intermediate results of pipeline stages for debugging/observability."
    )
    metadata: Dict[str, Any] = Field(
        {}, description="Additional pipeline-level information, e.g., total_latency_ms, cost_estimation, LLM_model_used."
    )

# Basic Error Handling / Validation (Pydantic handles most of this inherently)
# Example: Ensure score is within a valid range if needed.
# For RetrievalResult:
# @field_validator('score')
# @classmethod
# def validate_score(cls, v: float) -> float:
#     if not (0 <= v <= 1 or -1 <= v <= 1): # Example range
#         raise ValueError("Score must be between 0 and 1 or -1 and 1.")
#     return v
# This level of validation might be better placed within the specific module that assigns scores,
# but Pydantic provides a mechanism if central validation is desired.